# Generated by Django 5.0.7 on 2024-07-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_farming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherslide',
            name='image',
            field=models.ImageField(upload_to='weather_slides', verbose_name='Изображение'),
        ),
    ]
