# Generated by Django 5.0.7 on 2024-07-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_farming', '0002_alter_weatherslide_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(max_length=400, verbose_name='Описание')),
                ('concentration', models.TextField(max_length=100, verbose_name='Концентрация')),
                ('image', models.ImageField(upload_to='brand_logos', verbose_name='Логотип')),
                ('type', models.TextField(max_length=100, verbose_name='Тип продукта')),
                ('substance', models.TextField(max_length=100, verbose_name='Действующее вещество')),
                ('preparative', models.TextField(max_length=100, verbose_name='Препаративная форма')),
                ('consumption', models.TextField(max_length=100, verbose_name='Норма расхода')),
                ('packaging', models.TextField(max_length=100, verbose_name='Упаковка')),
                ('expiration', models.TextField(max_length=100, verbose_name='Срок годности')),
            ],
            options={
                'verbose_name': 'препарат',
                'verbose_name_plural': 'Препараты',
            },
        ),
    ]
