# Generated by Django 5.0.7 on 2024-07-30 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco_farming', '0003_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='concentration',
        ),
    ]
