# Generated by Django 5.0.7 on 2024-07-30 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_farming', '0005_alter_brand_consumption_alter_brand_expiration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(upload_to='product_categories', verbose_name='Изображение')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='product_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eco_farming.productcategory', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
