# Generated by Django 5.0.7 on 2024-07-30 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_farming', '0006_productcategory_brand_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='product_category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='eco_farming.productcategory', verbose_name='Категория'),
        ),
    ]
