# Generated by Django 5.0.7 on 2024-07-31 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_farming', '0008_alter_brand_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'категория продукта', 'verbose_name_plural': 'Категории продуктов'},
        ),
        migrations.CreateModel(
            name='BrandEffectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='brand_effect_images', verbose_name='Изображение')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eco_farming.brand', verbose_name='Товар')),
            ],
        ),
    ]
