# Generated by Django 5.0.7 on 2024-08-01 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_farming', '0010_alter_brandeffectimage_options_brandusageitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandeffectimage',
            options={'verbose_name': 'действие препарата', 'verbose_name_plural': 'Действие препаратов'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'категория препаратов', 'verbose_name_plural': 'Категории препаратов'},
        ),
        migrations.CreateModel(
            name='BrandAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=400, verbose_name='Описание')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eco_farming.brand', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'преимущество',
                'verbose_name_plural': 'Преимущества препаратов',
            },
        ),
    ]
