# Generated by Django 5.0.7 on 2024-08-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_farming', '0011_alter_brandeffectimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandadvantage',
            options={'verbose_name': 'преимущество', 'verbose_name_plural': 'Преимущества препарата'},
        ),
        migrations.AlterModelOptions(
            name='brandeffectimage',
            options={'verbose_name': 'действие препарата', 'verbose_name_plural': 'Действие препарата'},
        ),
        migrations.AlterField(
            model_name='brandadvantage',
            name='description',
            field=models.CharField(max_length=400, verbose_name='Описание'),
        ),
    ]
