# Generated by Django 5.0.7 on 2024-08-01 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_farming', '0012_alter_brandadvantage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harmful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('title_latin', models.CharField(max_length=100, verbose_name='Название (лат.)')),
                ('image', models.ImageField(upload_to='harmful_logos', verbose_name='Изображение (главное)')),
                ('description', models.TextField(max_length=600, verbose_name='Описание')),
                ('type', models.CharField(choices=[('Сорняки', 'Сорняки'), ('Болезни', 'Болезни'), ('Вредители', 'Вредители')], max_length=100, verbose_name='Тип')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('family', models.CharField(max_length=100, verbose_name='Семейство')),
                ('subtype', models.CharField(max_length=100, verbose_name='Подтип')),
                ('bio_group', models.CharField(max_length=100, verbose_name='Биологическая группа')),
                ('biology', models.TextField(max_length=400, verbose_name='Биология')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eco_farming.productcategory', verbose_name='Категория препаратов')),
            ],
            options={
                'verbose_name': 'вредный объект',
                'verbose_name_plural': 'Вредные объекты',
            },
        ),
        migrations.CreateModel(
            name='HarmfulImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='brand_effect_images', verbose_name='Изображение')),
                ('harmful', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eco_farming.harmful', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
