# Generated by Django 5.0.7 on 2024-08-01 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_farming', '0013_harmful_harmfulimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarmfulCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'категория вредных объектов',
                'verbose_name_plural': 'Категории вредных объектов',
            },
        ),
        migrations.AlterField(
            model_name='harmful',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eco_farming.harmfulcategory', verbose_name='Категория'),
        ),
    ]
