# Generated by Django 5.0.7 on 2024-08-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_farming', '0015_harmfulcategory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harmfulcategory',
            name='type',
            field=models.CharField(choices=[('Сорняки', 'Сорняки'), ('Болезни', 'Болезни'), ('Вредители', 'Вредители')], max_length=100, verbose_name='Тип'),
        ),
    ]
