# Generated by Django 5.0.7 on 2024-08-01 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco_farming', '0016_alter_harmfulcategory_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harmful',
            name='type',
        ),
    ]
