# Generated by Django 5.0.7 on 2024-08-03 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco_farming', '0018_culturecategory_culturebrands_culture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='culture',
            old_name='culture',
            new_name='category',
        ),
    ]
