# Generated by Django 5.0.7 on 2024-08-03 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_farming', '0019_rename_culture_culture_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'категория публикаций',
                'verbose_name_plural': 'Категории публикаций',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Наука', 'Наука'), ('Публикация', 'Публикация'), ('Видеоматериал', 'Видеоматериал')], max_length=100, verbose_name='Тип публикации')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='publications_main_images', verbose_name='Изображение (главное) или превью видео')),
                ('video', models.FileField(blank=True, upload_to='publications_videos')),
                ('description', models.TextField(max_length=600, verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата размещения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eco_farming.publicationcategory', verbose_name='Категория публикации')),
            ],
            options={
                'verbose_name': 'публикация',
                'verbose_name_plural': 'Публикации',
            },
        ),
        migrations.CreateModel(
            name='PublicationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='publications_images', verbose_name='Изображение')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eco_farming.publication', verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
