# Generated by Django 5.0.7 on 2024-08-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_farming', '0020_publicationcategory_publication_publicationimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='type',
            field=models.CharField(choices=[('Наука', 'Наука'), ('Публикации', 'Публикации'), ('Видеоматериалы', 'Видеоматериалы')], max_length=100, verbose_name='Тип публикации'),
        ),
    ]
