# Generated by Django 5.0.7 on 2024-08-04 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco_farming', '0023_headerimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headerimage',
            old_name='title',
            new_name='path',
        ),
    ]
