# Generated by Django 5.0.7 on 2024-08-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_farming', '0024_rename_title_headerimage_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerimage',
            name='title',
            field=models.CharField(default=2, max_length=100, verbose_name='Название страницы'),
            preserve_default=False,
        ),
    ]
