# Generated by Django 5.0.7 on 2024-08-04 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco_farming', '0025_headerimage_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headerimage',
            options={'verbose_name': 'изображение для шапки страницы', 'verbose_name_plural': 'Изображения для шапок страниц'},
        ),
    ]
