# Generated by Django 5.0.7 on 2024-08-07 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_farming', '0026_alter_headerimage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eco_farming.culturecategory', verbose_name='Категория'),
        ),
    ]
