# Generated by Django 5.0.7 on 2024-08-14 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_farming', '0027_alter_culture_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='culturecategory',
            name='image',
            field=models.ImageField(upload_to='culture_categories', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='harmful',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eco_farming.productcategory', verbose_name='Продукт'),
        ),
    ]
