# Generated by Django 5.0.7 on 2024-08-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_farming', '0028_alter_productcategory_options_brand_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='effect',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Действие'),
        ),
    ]
