# Generated by Django 5.0.7 on 2024-08-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_farming', '0030_harmful_slug_harmfulcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harmfulcategory',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
