# Generated by Django 5.0.7 on 2024-08-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_farming', '0031_alter_harmfulcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='culturecategory',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
