# Generated by Django 5.0.7 on 2024-08-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_farming', '0032_culture_slug_culturecategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
