# Generated by Django 5.0.7 on 2024-08-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_farming', '0033_publication_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
