# Generated by Django 5.0.7 on 2024-08-16 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_farming', '0034_alter_publication_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_numbers', models.TextField(max_length=600, verbose_name='Телефоны для связи:')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта:')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'страница контактов',
                'verbose_name_plural': 'Страницы контактов',
            },
        ),
        migrations.CreateModel(
            name='ContactsPageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование')),
                ('description', models.TextField(max_length=600, verbose_name='Контактные данные')),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер телефона')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eco_farming.contactspage', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'контактное лицо',
                'verbose_name_plural': 'контактные лица',
            },
        ),
    ]
