# Generated by Django 5.0.7 on 2024-08-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_farming', '0036_companypage_alter_contactspage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='effect',
            field=models.TextField(blank=True, null=True, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='companypage',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='companypage',
            name='description_2',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='contactspage',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
