# Generated by Django 5.0.7 on 2024-08-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_farming', '0038_culture_brand_culturecategory_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harmful',
            name='product_category',
        ),
        migrations.AddField(
            model_name='harmful',
            name='brand',
            field=models.ManyToManyField(blank=True, to='eco_farming.brand', verbose_name='Продукты (опционально)'),
        ),
    ]
