# Generated by Django 5.0.7 on 2024-08-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_farming', '0039_remove_harmful_product_category_harmful_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandusageitem',
            name='saboteur',
            field=models.CharField(max_length=100, verbose_name='Вредный объект'),
        ),
    ]
